image: elixir:1.5

services:
  - postgres:10

variables:
  MIX_ENV: "test"
  DB_USERNAME: "postgres"
  DB_HOSTNAME: "postgres"
  GLOBAL_MAIL_SENDER: "support@freshcom.io"

before_script:
  - apt-get update
  - apt-get install -y postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  - mix ecto.reset

test:
  only:
    - develop
    - master
  script:
    - mix coveralls test/blue_jet
